sudo: false
before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
language: scala
jdk:
  - oraclejdk8
  - openjdk11
scala:
- 2.12.7
script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalafmtCheck scalafmtSbtCheck
after_success:
- sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt ++$TRAVIS_SCALA_VERSION releaseEarly;
  fi
before_install:
- if [ -n "${TRAVIS_TAG}" && $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_dcc5d8de5fcf_key
  -iv $encrypted_dcc5d8de5fcf_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi
branches:
  only:
  - master
  - /^v.*$/
