# Use container-based infrastructure
sudo: false

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

language: scala

jdk: oraclejdk8

scala:
   - 2.12.7

script:
   - sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalafmtCheck scalafmtSbtCheck

after_success:
   - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
