name: Build

on:
  pull_request:
    branches: [series/3.x.x]
  push:
    branches: [series/3.x.x]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/coursier/v1
            ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: "Starting up MinIO 🐳"
        run: docker-compose up -d
      - name: "list streams"
        run: AWS_SECRET_ACCESS_KEY=dummy AWS_ACCESS_KEY_ID=dummy AWS_REGION=us-east-1 aws --endpoint-url=http://localhost:4566 kinesis list-streams
      - name: Run tests
        run: sbt +clean +test +doc
        env:
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
      - name: "Shutting down MinIO 🐳"
        run: docker-compose down
