name: Scala

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2.1.0"

      - name: "Starting up MinIO 🐳"
        run: docker-compose up -d

      - name: "Running shasum"
        run: |
          shasum build.sbt \
            project/plugins.sbt \
            project/build.properties \
            project/V.scala > gha.cache.tmp

      - name: "~/.sbt cache"
        uses: "actions/cache@v1"
        with:
          key: "${{ runner.os }}-sbt-${{ hashFiles('gha.cache.tmp') }}"
          path: "~/.sbt"
          restore-keys: sbt

      - name: "~/.cache/coursier cache"
        uses: "actions/cache@v1"
        with:
          key: "${{ runner.os }}-coursier-${{ hashFiles('gha.cache.tmp') }}"
          path: "~/.cache/coursier"
          restore-keys: coursier

      - name: "Java ${{ matrix.java}} setup"
        uses: "olafurpg/setup-java@v6"
        with:
          java-version: "${{ matrix.java}}"

      - name: "Scala tests & coverage"
        run: "sbt coverage test scalafmtCheck scalafmtSbtCheck"

      - name: "Shutting down MinIO 🐳"
        run: docker-compose down
    strategy:
      matrix:
        java:
          - '8.0.242'
          - '11.0.5'
